-- MySQL Script generated by MySQL Workbench
-- 05/20/16 11:32:43
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ssh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ssh` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ssh` ;

-- -----------------------------------------------------
-- Table `ssh`.`t_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssh`.`t_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `roleName` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssh`.`t_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssh`.`t_account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `accountTel` VARCHAR(45) NULL,
  `accountName` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `loginName` VARCHAR(45) NULL,
  `loginTime` VARCHAR(45) NULL,
  `createtime` VARCHAR(45) NULL,
  `loginIp` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `roleid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_account_t_role_idx` (`roleid` ASC),
  CONSTRAINT `fk_t_account_t_role`
    FOREIGN KEY (`roleid`)
    REFERENCES `ssh`.`t_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssh`.`t_dept`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssh`.`t_dept` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `deptName` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssh`.`t_disease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssh`.`t_disease` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `diseaseName` VARCHAR(45) NULL,
  `deptId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_disease_t_dept1_idx` (`deptId` ASC),
  CONSTRAINT `fk_t_disease_t_dept1`
    FOREIGN KEY (`deptId`)
    REFERENCES `ssh`.`t_dept` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssh`.`t_insurance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssh`.`t_insurance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `insurName` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssh`.`t_paitent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssh`.`t_paitent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `sex` TINYINT NULL,
  `card` VARCHAR(45) NULL,
  `age` INT NULL,
  `tel` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `allergy` LONGTEXT NULL COMMENT '过敏史',
  `text` LONGTEXT NULL,
  `createtime` VARCHAR(45) NULL,
  `insurId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_paitent_t_insurance1_idx` (`insurId` ASC),
  CONSTRAINT `fk_t_paitent_t_insurance1`
    FOREIGN KEY (`insurId`)
    REFERENCES `ssh`.`t_insurance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssh`.`t_visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssh`.`t_visit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `chuzhen` VARCHAR(200) NULL,
  `zhengzhuang` LONGTEXT NULL,
  `bingshi` LONGTEXT NULL,
  `tizheng` LONGTEXT NULL,
  `jieguo` LONGTEXT NULL,
  `fangan` LONGTEXT NULL,
  `peihu` VARCHAR(45) NULL,
  `createtime` VARCHAR(45) NULL,
  `nexttime` VARCHAR(45) NULL,
  `path` VARCHAR(45) NULL,
  `paitentId` INT NOT NULL,
  `deptId` INT NOT NULL,
  `diseaseId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_visit_t_paitent1_idx` (`paitentId` ASC),
  INDEX `fk_t_visit_t_dept1_idx` (`deptId` ASC),
  INDEX `fk_t_visit_t_disease1_idx` (`diseaseId` ASC),
  CONSTRAINT `fk_t_visit_t_paitent1`
    FOREIGN KEY (`paitentId`)
    REFERENCES `ssh`.`t_paitent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_visit_t_dept1`
    FOREIGN KEY (`deptId`)
    REFERENCES `ssh`.`t_dept` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_visit_t_disease1`
    FOREIGN KEY (`diseaseId`)
    REFERENCES `ssh`.`t_disease` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
